config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo.wp5dtc1/dtc51:
      branch: ST510111
      repo: https://gitlab.com/dtgeo.wp5dtc1/dtc51.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-salmon-jellyfish.sh
        container: qc.acc_snappy-zucchini-wildebeest
  QC.Doc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-flax-capuchin.sh
        container: qc.doc_squirrely-pumpkin-bird
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-tangerine-frise.sh
        container: qc.doc_lovely-cerise-hound
  QC.Lic:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-crimson-toucan.sh
        container: qc.lic_woozy-bronze-grouse
  QC.Sec:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-lavender-duck.sh
        container: qc.sec_flaky-wheat-barnacle
  QC.Sty:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-periwinkle-crab.sh
        container: qc.sty_gummy-cornflower-snake
  QC.Uni:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-sangria-tang.sh
        container: qc.uni_crabby-razzmatazz-toad
  QC.Ver:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-sapphire-dugong.sh
        container: qc.ver_flabby-harlequin-lizard
timeout: 5400
