config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo.wp5dtc1/dtc51:
      branch: ST510109
      repo: https://gitlab.com/dtgeo.wp5dtc1/dtc51.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cerulean-jackal.sh
        container: qc.acc_thirsty-xanthic-chameleon
  QC.Doc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-copper-owl.sh
        container: qc.doc_sickly-lilac-millipede
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-sepia-abyssinian.sh
        container: qc.doc_tacky-green-seal
      gitlab.com/dtgeo.wp5dtc1/dtc51 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ivory-spider.sh
        container: qc.doc_greasy-myrtle-fly
  QC.Lic:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-gold-dalmatian.sh
        container: qc.lic_blurry-goldenrod-budgerigar
  QC.Sec:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cinnabar-bat.sh
        container: qc.sec_squeaky-white-burmese
  QC.Sty:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-salmon-crane.sh
        container: qc.sty_blurry-lemon-dormouse
      gitlab.com/dtgeo.wp5dtc1/dtc51 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-xanthic-rhinoceros.sh
        container: qc.sty_gimpy-turquoise-audemer
  QC.Uni:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-bistre-shrimp.sh
        container: qc.uni_sickly-saffron-wasp
  QC.Ver:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lavender-pig.sh
        container: qc.ver_homely-wisteria-robin
timeout: 5400
